return {
  -- 'akinsho/bufferline.nvim',
  -- version = "v3.*",
  -- dependencies = {
  --   'nvim-tree/nvim-web-devicons',
  --   'echasnovski/mini.bufremove',
  -- },
  -- lazy = false,
  -- keys = {
  --   { "H", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev buffer" },
  --   { "L", "<cmd>BufferLineCycleNext<cr>", desc = "Next buffer" },
  --   { "<leader>bd", "<cmd>lua require('mini.bufremove').delete()<cr>", desc = "Delete Buffer" },
  -- },
  -- config = function()
  --   local icons = {
  --     Error = " ",
  --     Warn = " ",
  --   }
  --
  --   require("bufferline").setup({
  --     options = {
  --       close_command = function(n) require("mini.bufremove").delete(n, false) end,
  --       right_mouse_command = function(n) require("mini.bufremove").delete(n, false) end,
  --       diagnostics = "nvim_lsp",
  --       always_show_bufferline = true,
  --       diagnostics_indicator = function(_, _, diag)
  --         local ret = (diag.error and icons.Error .. diag.error .. " " or "")
  --           .. (diag.warning and icons.Warn .. diag.warning or "")
  --         return vim.trim(ret)
  --       end,
  --       offsets = {
  --         {
  --           filetype = "neo-tree",
  --           text = "Neo-tree",
  --           highlight = "Directory",
  --           text_align = "left",
  --         },
  --       },
  --     },
  --   })
  -- end,
}
